-- =========================================================================
-- LATHA JEWELLERY WORKS ATELIER - SUPABASE CLOUD DATABASE SCHEMA
-- Execute this script in the Supabase SQL Editor (Dashboard > SQL Editor)
-- to initialize all persistent tables for the website & admin studio.
-- =========================================================================

-- 1. Enable UUID Extension (Optional/Helpful)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 2. CATEGORIES TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    display_order INT DEFAULT 1,
    active INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 3. JEWELLERY MODELS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.jewellery_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_slug TEXT NOT NULL,
    description TEXT,
    min_weight TEXT,
    primary_image TEXT NOT NULL,
    additional_images JSONB DEFAULT '[]'::jsonb,
    featured INT DEFAULT 0,
    active INT DEFAULT 1,
    display_order INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 4. HERO BANNERS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    desktop_image TEXT,
    mobile_image TEXT,
    cta_label TEXT DEFAULT 'Enquire Now',
    cta_link TEXT DEFAULT '#catalogue',
    active INT DEFAULT 1,
    display_order INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 5. LIVE & BOARD GOLD RATES TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.gold_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_24k TEXT NOT NULL,
    rate_22k TEXT NOT NULL,
    rate_18k TEXT NOT NULL,
    rate_silver TEXT DEFAULT '95',
    price_24k NUMERIC,
    price_22k NUMERIC,
    price_18k NUMERIC,
    currency TEXT DEFAULT 'INR',
    unit TEXT DEFAULT 'gram',
    source TEXT DEFAULT 'GoldAPI.io (Live)',
    status TEXT DEFAULT 'Connected (Live)',
    mode TEXT DEFAULT 'AUTOMATIC_API',
    ticker_visible INT DEFAULT 1,
    last_updated TEXT,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 6. PATRON REVIEWS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT DEFAULT 'Patron',
    rating INT DEFAULT 5,
    review_text TEXT NOT NULL,
    status TEXT DEFAULT 'PENDING', -- 'PENDING', 'APPROVED', 'REJECTED'
    featured INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 7. CUSTOM ENQUIRIES TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    email TEXT,
    jewellery_type TEXT DEFAULT 'Custom Design',
    requirements TEXT,
    status TEXT DEFAULT 'NEW', -- 'NEW', 'CONTACTED', 'IN PROGRESS', 'COMPLETED'
    internal_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 8. BRAND STORY & SITE CONTENT TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.site_content (
    id INT PRIMARY KEY DEFAULT 1,
    content JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 9. BUSINESS SETTINGS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.business_settings (
    id INT PRIMARY KEY DEFAULT 1,
    settings JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 10. ADMIN USERS TABLE (Database Authorization & RBAC)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'admin', -- 'admin', 'super_admin'
    status TEXT NOT NULL DEFAULT 'active', -- 'active', 'inactive', 'suspended'
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- 11. ROW LEVEL SECURITY (RLS) POLICIES
-- Permissive read for public storefront, write access for service-role/admin
-- =========================================================================
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jewellery_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gold_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Allow public read of active store data
DROP POLICY IF EXISTS "Public can view categories" ON public.categories;
CREATE POLICY "Public can view categories" ON public.categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view jewellery_models" ON public.jewellery_models;
CREATE POLICY "Public can view jewellery_models" ON public.jewellery_models FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view banners" ON public.banners;
CREATE POLICY "Public can view banners" ON public.banners FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view gold_rates" ON public.gold_rates;
CREATE POLICY "Public can view gold_rates" ON public.gold_rates FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view approved reviews" ON public.reviews;
CREATE POLICY "Public can view approved reviews" ON public.reviews FOR SELECT USING (status = 'APPROVED');

DROP POLICY IF EXISTS "Public can submit reviews" ON public.reviews;
CREATE POLICY "Public can submit reviews" ON public.reviews FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public can submit enquiries" ON public.enquiries;
CREATE POLICY "Public can submit enquiries" ON public.enquiries FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public can view site_content" ON public.site_content;
CREATE POLICY "Public can view site_content" ON public.site_content FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view business_settings" ON public.business_settings;
CREATE POLICY "Public can view business_settings" ON public.business_settings FOR SELECT USING (true);

-- Allow full access for service_role (Admin API key)
DROP POLICY IF EXISTS "Service role full access categories" ON public.categories;
CREATE POLICY "Service role full access categories" ON public.categories USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access jewellery_models" ON public.jewellery_models;
CREATE POLICY "Service role full access jewellery_models" ON public.jewellery_models USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access banners" ON public.banners;
CREATE POLICY "Service role full access banners" ON public.banners USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access gold_rates" ON public.gold_rates;
CREATE POLICY "Service role full access gold_rates" ON public.gold_rates USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access reviews" ON public.reviews;
CREATE POLICY "Service role full access reviews" ON public.reviews USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access enquiries" ON public.enquiries;
CREATE POLICY "Service role full access enquiries" ON public.enquiries USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access site_content" ON public.site_content;
CREATE POLICY "Service role full access site_content" ON public.site_content USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access business_settings" ON public.business_settings;
CREATE POLICY "Service role full access business_settings" ON public.business_settings USING (true) WITH CHECK (true);

-- =========================================================================
-- 11. INITIAL SEED DATA INSERTION
-- =========================================================================

-- Seed Categories
INSERT INTO public.categories (id, slug, name, description, image_url, display_order, active)
VALUES
(1, 'chain', 'Chains & Necklaces', 'Traditional South Indian chains, royal interlock, and heavy necklaces', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnskaVKp4AGGJ79HeuyN4y4eMStueunvHzx12Hmb2ujC1ApDVQFiak_UH3jVcFbhBwb6cCO9-3iy42vxquH8x_cY3vFjxrI66X4grNpvOH3ai_XjfbWz1PE3jdivj0IC-sLGEoYhQcNrwt4IHnP1kyUPMEahTpb9kCd01Cu5_bH9LDSob6yISF95MGbG1asDCuOXW8bI_418peCJD2DOmaM5oWQ3HEE48Ln-9FXFdpTwnO_ie3TytU5w', 1, 1),
(2, 'kolus', 'Kolus (Anklets)', 'Handcrafted solid gold and silver kolus with ghungroo bells', 'https://lh3.googleusercontent.com/aida-public/AB6AXuARGVXDagX1I0wU7qeCCwtpbMzlW2w0l8sCdqvHXv2-QxCrdiPh7TX0m0Hd3mcS0QdHzcoeM3jEU4pd5jyBvkqVxjTzZxHDb0x35LpZH-i_e-fDoy10rc7wLGub-ZLDl-DgL1lTPj8SygN5AAVP_7RxyMVQMB3zGKfUUAwRcFING5YxPmGvDbpRkfB5mZc-cESp_NJHU26hF0sPgskmiYog0CQI2tp9FF5Ojw_hP94YUZcy42jhzYg', 2, 1),
(3, 'kammal', 'Kammal (Earrings)', 'Antique temple jimkis, jhumkas, chandeliers, and handcrafted studs', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgXuR9HZ2L03yoh7a4cPcY3dmCjytQ6S3bjHybTIWpFN3-Q3gRZLwhnqvQb6W-Vc0KqXGSOoz3NK8j1cLutVDM0dqMvS1XTmm8QFeMAFXGaZ1qNo2piEPRgQRCSDzSt30sE4JW8HM6iX2zAKpxhKleZPCh2zNOha5rtx4hwdoKUiMsnF4_t1FlCSjl8JNrAM6Ecs2QyC8dYF01waC6UwOqV-z3g198ten31-6HiOnZpEaeuV-hAVdwRw', 3, 1),
(4, 'bangles', 'Bangles & Bracelets', 'Hand-engraved 22k gold bangles, antique kadas, and valayal sets', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBLl7BdsBtE3bAuXGjSQphqRGgSOlMSn-A62GrkIUdmng0l33UqV3OMvoX5GRSvt09wmFmLxmAzpFV4icbVbUyiviMQcMYUeFwY4xeGI-rnjeR97xrNVJ8H4ETGX16FsVbKGRGH_TppL9-XfcJkS07QQGLXFjJkQ4j4c--88RW24hElwfLSZCGIAp_weUgjY__PhS6AeXylhnRZV1QitOJmwJ88u72vxTEqSqUGCojkj2no13jOsskmaw', 4, 1),
(5, 'rings', 'Rings', 'Regal filigree engagement bands, signet rings, and gemstone studs', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBjH0Wf92nSb6Ea9999evorQ-Ofyk3D1-TfcWgvTtd11AFIcAjqcps2kNorL-vgVS41vhD91B03s2T5uHFjiPDfNY5Gky0DyihyQ37CchFeP5AIbtCCwgfv-YGZTmbG0WIK042p0OcaQjI3astHLHSVy8rUhi8UgTO-1AEzybWxxfquSXFF-L2jHCUNA2KihtbTyNPyBPwM_ufBvGWLoq4DlKdYhS0Ba-6s5ppWFzdwXp97rOrXjcN2LQ', 5, 1)
ON CONFLICT (id) DO NOTHING;

-- Seed Initial Gold Rates (Realistic 2026 Board Rates)
INSERT INTO public.gold_rates (id, rate_24k, rate_22k, rate_18k, rate_silver, price_24k, price_22k, price_18k, currency, unit, source, status, mode, ticker_visible, last_updated)
VALUES (1, '13,289', '12,182', '9,967', '95', 13289, 12182, 9967, 'INR', 'gram', 'GoldAPI.io (Live)', 'Connected (Live)', 'AUTOMATIC_API', 1, '23 Sept 2026, 04:57 pm')
ON CONFLICT (id) DO NOTHING;

-- Storage Bucket for jewellery images (if using Supabase Storage)
INSERT INTO storage.buckets (id, name, public)
VALUES ('jewellery-images', 'jewellery-images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public can view jewellery-images" ON storage.objects;
CREATE POLICY "Public can view jewellery-images" ON storage.objects FOR SELECT USING (bucket_id = 'jewellery-images');

DROP POLICY IF EXISTS "Authenticated users can upload jewellery-images" ON storage.objects;
CREATE POLICY "Authenticated users can upload jewellery-images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'jewellery-images');

-- =========================================================================
-- 12. ADMIN USERS RLS POLICIES & PRIMARY OWNER ASSOCIATION
-- =========================================================================
-- Drop any legacy or overly permissive policies
DROP POLICY IF EXISTS "Allow select for admin check" ON public.admin_users;
DROP POLICY IF EXISTS "Public check admin status" ON public.admin_users;
DROP POLICY IF EXISTS "Users can read own admin record" ON public.admin_users;

-- Secure RLS: Only authenticated users can read their OWN authorization record
CREATE POLICY "Users can read own admin record"
ON public.admin_users
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

-- Service role retains administrative management access server-side
DROP POLICY IF EXISTS "Service role full access admin_users" ON public.admin_users;
CREATE POLICY "Service role full access admin_users"
ON public.admin_users
USING (true)
WITH CHECK (true);

-- Seed / Upsert Primary Administrator (idempotent, safely linking auth user UUID if present)
INSERT INTO public.admin_users (user_id, email, role, status)
VALUES (
    (SELECT id FROM auth.users WHERE lower(email) = lower('lathajewelleryworks@gmail.com') LIMIT 1),
    'lathajewelleryworks@gmail.com',
    'admin',
    'active'
)
ON CONFLICT (email) DO UPDATE
SET user_id = COALESCE(
        public.admin_users.user_id,
        EXCLUDED.user_id,
        (SELECT id FROM auth.users WHERE lower(email) = lower('lathajewelleryworks@gmail.com') LIMIT 1)
    ),
    role = 'admin',
    status = 'active',
    updated_at = NOW();

-- Safely associate user_id if auth.users already contains the user
UPDATE public.admin_users
SET
    user_id = (
        SELECT id
        FROM auth.users
        WHERE lower(email) = lower('lathajewelleryworks@gmail.com')
        LIMIT 1
    ),
    role = 'admin',
    status = 'active',
    updated_at = NOW()
WHERE lower(email) = lower('lathajewelleryworks@gmail.com')
  AND (user_id IS NULL OR user_id != (SELECT id FROM auth.users WHERE lower(email) = lower('lathajewelleryworks@gmail.com') LIMIT 1));


