CREATE TABLE IF NOT EXISTS public.gold_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price_24k NUMERIC(12,2) NOT NULL,
  price_22k NUMERIC(12,2) NOT NULL,
  price_18k NUMERIC(12,2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'INR',
  unit TEXT NOT NULL DEFAULT 'gram',
  source TEXT NOT NULL DEFAULT 'GoldAPI',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.gold_rates ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'public' 
      AND tablename = 'gold_rates' 
      AND policyname = 'Public can read gold rates'
  ) THEN
    CREATE POLICY "Public can read gold rates"
    ON public.gold_rates
    FOR SELECT
    TO anon, authenticated
    USING (true);
  END IF;
END $$;
